version: '3.8'

services:
  api:
    image: datascientest/fastapi:1.0.0
    ports:
      - "8000:8000"

  auth_test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TEST_FILE=auth_test.py
    environment:
      - LOG=1
    volumes:
      - ./results:/results
    depends_on:
      - api

  authz_test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TEST_FILE=authz_test.py
    environment:
      - LOG=1
    volumes:
      - ./results:/results
    depends_on:
      - api

  content_test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TEST_FILE=content_test.py
    environment:
      - LOG=1
    volumes:
      - ./results:/results
    depends_on:
      - api
